DROP TABLE CHIMAC;
DROP TABLE REVIEW;
DROP TABLE  BASKET;

SELECT * FROM CHIMAC;
SELECT * FROM REVIEW;
SELECT * FROM BASKET;

-- 메인 테이블--
CREATE TABLE CHIMAC( 
    CMID         NVARCHAR2(12) PRIMARY KEY,  -- 아이디
    CMPW         NVARCHAR2(20) NOT NULL,  -- 비밀번호
    CMNAME       NVARCHAR2(5) NOT NULL,   -- 이름 
    CMBIR        DATE NOT NULL,           -- 생년월일
    CMGEN        NVARCHAR2(2),   -- 성별
    CMEMAIL      NVARCHAR2(30),  -- 이메일
    CMADR        NVARCHAR2(99) NOT NULL,  -- 주소
    CMPHONE      NVARCHAR2(13) UNIQUE,  -- 전화번호
    CMBALANCE    NUMBER DEFAULT 0    -- 잔액  
);

--리뷰 테이블-
CREATE TABLE REVIEW(
CMID   NVARCHAR2(12),
MENUNAME NVARCHAR2(10),
REVIEWNO NUMBER (4) PRIMARY KEY,
REVIEW NVARCHAR2(100)
);

--장바구니 테이블
CREATE TABLE  BASKET(
MENUNAME NVARCHAR2(10),
PRICE   NUMBER(7)
);
